/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthSetPasswordRouteImport } from './routes/_auth/set-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthPasswordResetSentRouteImport } from './routes/_auth/password-reset-sent'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthAccountReadyRouteImport } from './routes/_auth/account-ready'
import { Route as LandingSellIndexRouteImport } from './routes/_landing/sell/index'
import { Route as LandingRentIndexRouteImport } from './routes/_landing/rent/index'
import { Route as LandingPricingIndexRouteImport } from './routes/_landing/pricing/index'
import { Route as LandingContactIndexRouteImport } from './routes/_landing/contact/index'
import { Route as LandingBuyIndexRouteImport } from './routes/_landing/buy/index'
import { Route as LandingBlogIndexRouteImport } from './routes/_landing/blog/index'
import { Route as LandingAboutIndexRouteImport } from './routes/_landing/about/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardPropertiesIndexRouteImport } from './routes/_dashboard/properties/index'
import { Route as DashboardPerformanceIndexRouteImport } from './routes/_dashboard/performance/index'
import { Route as DashboardPendingApprovalsIndexRouteImport } from './routes/_dashboard/pending-approvals/index'
import { Route as DashboardMessagesIndexRouteImport } from './routes/_dashboard/messages/index'
import { Route as DashboardManagersIndexRouteImport } from './routes/_dashboard/managers/index'
import { Route as DashboardListingIndexRouteImport } from './routes/_dashboard/listing/index'
import { Route as DashboardInsightsIndexRouteImport } from './routes/_dashboard/insights/index'
import { Route as DashboardGettingStartedIndexRouteImport } from './routes/_dashboard/getting-started/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardBlogsIndexRouteImport } from './routes/_dashboard/blogs/index'
import { Route as DashboardAdminInsightsIndexRouteImport } from './routes/_dashboard/admin-insights/index'
import { Route as LandingSellIdRouteImport } from './routes/_landing/sell/$id'
import { Route as LandingRentIdRouteImport } from './routes/_landing/rent/$id'
import { Route as LandingBuyIdRouteImport } from './routes/_landing/buy/$id'
import { Route as LandingBlogIdRouteImport } from './routes/_landing/blog/$id'
import { Route as DashboardPropertiesCreateRouteImport } from './routes/_dashboard/properties/create'
import { Route as DashboardPropertiesIdRouteImport } from './routes/_dashboard/properties/$id'
import { Route as DashboardListingIdRouteImport } from './routes/_dashboard/listing/$id'
import { Route as DashboardBlogsCreateRouteImport } from './routes/_dashboard/blogs/create'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPasswordResetSentRoute = AuthPasswordResetSentRouteImport.update({
  id: '/password-reset-sent',
  path: '/password-reset-sent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountReadyRoute = AuthAccountReadyRouteImport.update({
  id: '/account-ready',
  path: '/account-ready',
  getParentRoute: () => AuthRoute,
} as any)
const LandingSellIndexRoute = LandingSellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingRentIndexRoute = LandingRentIndexRouteImport.update({
  id: '/rent/',
  path: '/rent/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPricingIndexRoute = LandingPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingContactIndexRoute = LandingContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBuyIndexRoute = LandingBuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBlogIndexRoute = LandingBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAboutIndexRoute = LandingAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesIndexRoute =
  DashboardPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPerformanceIndexRoute =
  DashboardPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPendingApprovalsIndexRoute =
  DashboardPendingApprovalsIndexRouteImport.update({
    id: '/pending-approvals/',
    path: '/pending-approvals/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMessagesIndexRoute = DashboardMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManagersIndexRoute = DashboardManagersIndexRouteImport.update({
  id: '/managers/',
  path: '/managers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingIndexRoute = DashboardListingIndexRouteImport.update({
  id: '/listing/',
  path: '/listing/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsIndexRoute = DashboardInsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGettingStartedIndexRoute =
  DashboardGettingStartedIndexRouteImport.update({
    id: '/getting-started/',
    path: '/getting-started/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogsIndexRoute = DashboardBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminInsightsIndexRoute =
  DashboardAdminInsightsIndexRouteImport.update({
    id: '/admin-insights/',
    path: '/admin-insights/',
    getParentRoute: () => DashboardRoute,
  } as any)
const LandingSellIdRoute = LandingSellIdRouteImport.update({
  id: '/sell/$id',
  path: '/sell/$id',
  getParentRoute: () => LandingRoute,
} as any)
const LandingRentIdRoute = LandingRentIdRouteImport.update({
  id: '/rent/$id',
  path: '/rent/$id',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBuyIdRoute = LandingBuyIdRouteImport.update({
  id: '/buy/$id',
  path: '/buy/$id',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBlogIdRoute = LandingBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardPropertiesCreateRoute =
  DashboardPropertiesCreateRouteImport.update({
    id: '/properties/create',
    path: '/properties/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPropertiesIdRoute = DashboardPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingIdRoute = DashboardListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogsCreateRoute = DashboardBlogsCreateRouteImport.update({
  id: '/blogs/create',
  path: '/blogs/create',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/account-ready': typeof AuthAccountReadyRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/password-reset-sent': typeof AuthPasswordResetSentRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-password': typeof AuthSetPasswordRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/': typeof LandingIndexRoute
  '/blogs/create': typeof DashboardBlogsCreateRoute
  '/listing/$id': typeof DashboardListingIdRoute
  '/properties/$id': typeof DashboardPropertiesIdRoute
  '/properties/create': typeof DashboardPropertiesCreateRoute
  '/blog/$id': typeof LandingBlogIdRoute
  '/buy/$id': typeof LandingBuyIdRoute
  '/rent/$id': typeof LandingRentIdRoute
  '/sell/$id': typeof LandingSellIdRoute
  '/admin-insights': typeof DashboardAdminInsightsIndexRoute
  '/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/getting-started': typeof DashboardGettingStartedIndexRoute
  '/insights': typeof DashboardInsightsIndexRoute
  '/listing': typeof DashboardListingIndexRoute
  '/managers': typeof DashboardManagersIndexRoute
  '/messages': typeof DashboardMessagesIndexRoute
  '/pending-approvals': typeof DashboardPendingApprovalsIndexRoute
  '/performance': typeof DashboardPerformanceIndexRoute
  '/properties': typeof DashboardPropertiesIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/about': typeof LandingAboutIndexRoute
  '/blog': typeof LandingBlogIndexRoute
  '/buy': typeof LandingBuyIndexRoute
  '/contact': typeof LandingContactIndexRoute
  '/pricing': typeof LandingPricingIndexRoute
  '/rent': typeof LandingRentIndexRoute
  '/sell': typeof LandingSellIndexRoute
}
export interface FileRoutesByTo {
  '/account-ready': typeof AuthAccountReadyRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/password-reset-sent': typeof AuthPasswordResetSentRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-password': typeof AuthSetPasswordRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/': typeof LandingIndexRoute
  '/blogs/create': typeof DashboardBlogsCreateRoute
  '/listing/$id': typeof DashboardListingIdRoute
  '/properties/$id': typeof DashboardPropertiesIdRoute
  '/properties/create': typeof DashboardPropertiesCreateRoute
  '/blog/$id': typeof LandingBlogIdRoute
  '/buy/$id': typeof LandingBuyIdRoute
  '/rent/$id': typeof LandingRentIdRoute
  '/sell/$id': typeof LandingSellIdRoute
  '/admin-insights': typeof DashboardAdminInsightsIndexRoute
  '/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/getting-started': typeof DashboardGettingStartedIndexRoute
  '/insights': typeof DashboardInsightsIndexRoute
  '/listing': typeof DashboardListingIndexRoute
  '/managers': typeof DashboardManagersIndexRoute
  '/messages': typeof DashboardMessagesIndexRoute
  '/pending-approvals': typeof DashboardPendingApprovalsIndexRoute
  '/performance': typeof DashboardPerformanceIndexRoute
  '/properties': typeof DashboardPropertiesIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/about': typeof LandingAboutIndexRoute
  '/blog': typeof LandingBlogIndexRoute
  '/buy': typeof LandingBuyIndexRoute
  '/contact': typeof LandingContactIndexRoute
  '/pricing': typeof LandingPricingIndexRoute
  '/rent': typeof LandingRentIndexRoute
  '/sell': typeof LandingSellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_auth/account-ready': typeof AuthAccountReadyRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/password-reset-sent': typeof AuthPasswordResetSentRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/set-password': typeof AuthSetPasswordRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_landing/': typeof LandingIndexRoute
  '/_dashboard/blogs/create': typeof DashboardBlogsCreateRoute
  '/_dashboard/listing/$id': typeof DashboardListingIdRoute
  '/_dashboard/properties/$id': typeof DashboardPropertiesIdRoute
  '/_dashboard/properties/create': typeof DashboardPropertiesCreateRoute
  '/_landing/blog/$id': typeof LandingBlogIdRoute
  '/_landing/buy/$id': typeof LandingBuyIdRoute
  '/_landing/rent/$id': typeof LandingRentIdRoute
  '/_landing/sell/$id': typeof LandingSellIdRoute
  '/_dashboard/admin-insights/': typeof DashboardAdminInsightsIndexRoute
  '/_dashboard/blogs/': typeof DashboardBlogsIndexRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/getting-started/': typeof DashboardGettingStartedIndexRoute
  '/_dashboard/insights/': typeof DashboardInsightsIndexRoute
  '/_dashboard/listing/': typeof DashboardListingIndexRoute
  '/_dashboard/managers/': typeof DashboardManagersIndexRoute
  '/_dashboard/messages/': typeof DashboardMessagesIndexRoute
  '/_dashboard/pending-approvals/': typeof DashboardPendingApprovalsIndexRoute
  '/_dashboard/performance/': typeof DashboardPerformanceIndexRoute
  '/_dashboard/properties/': typeof DashboardPropertiesIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
  '/_landing/about/': typeof LandingAboutIndexRoute
  '/_landing/blog/': typeof LandingBlogIndexRoute
  '/_landing/buy/': typeof LandingBuyIndexRoute
  '/_landing/contact/': typeof LandingContactIndexRoute
  '/_landing/pricing/': typeof LandingPricingIndexRoute
  '/_landing/rent/': typeof LandingRentIndexRoute
  '/_landing/sell/': typeof LandingSellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account-ready'
    | '/forgot-password'
    | '/login'
    | '/password-reset-sent'
    | '/register'
    | '/reset-password'
    | '/set-password'
    | '/verify-otp'
    | '/'
    | '/blogs/create'
    | '/listing/$id'
    | '/properties/$id'
    | '/properties/create'
    | '/blog/$id'
    | '/buy/$id'
    | '/rent/$id'
    | '/sell/$id'
    | '/admin-insights'
    | '/blogs'
    | '/dashboard'
    | '/getting-started'
    | '/insights'
    | '/listing'
    | '/managers'
    | '/messages'
    | '/pending-approvals'
    | '/performance'
    | '/properties'
    | '/settings'
    | '/users'
    | '/about'
    | '/blog'
    | '/buy'
    | '/contact'
    | '/pricing'
    | '/rent'
    | '/sell'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account-ready'
    | '/forgot-password'
    | '/login'
    | '/password-reset-sent'
    | '/register'
    | '/reset-password'
    | '/set-password'
    | '/verify-otp'
    | '/'
    | '/blogs/create'
    | '/listing/$id'
    | '/properties/$id'
    | '/properties/create'
    | '/blog/$id'
    | '/buy/$id'
    | '/rent/$id'
    | '/sell/$id'
    | '/admin-insights'
    | '/blogs'
    | '/dashboard'
    | '/getting-started'
    | '/insights'
    | '/listing'
    | '/managers'
    | '/messages'
    | '/pending-approvals'
    | '/performance'
    | '/properties'
    | '/settings'
    | '/users'
    | '/about'
    | '/blog'
    | '/buy'
    | '/contact'
    | '/pricing'
    | '/rent'
    | '/sell'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_landing'
    | '/_auth/account-ready'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/password-reset-sent'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/set-password'
    | '/_auth/verify-otp'
    | '/_landing/'
    | '/_dashboard/blogs/create'
    | '/_dashboard/listing/$id'
    | '/_dashboard/properties/$id'
    | '/_dashboard/properties/create'
    | '/_landing/blog/$id'
    | '/_landing/buy/$id'
    | '/_landing/rent/$id'
    | '/_landing/sell/$id'
    | '/_dashboard/admin-insights/'
    | '/_dashboard/blogs/'
    | '/_dashboard/dashboard/'
    | '/_dashboard/getting-started/'
    | '/_dashboard/insights/'
    | '/_dashboard/listing/'
    | '/_dashboard/managers/'
    | '/_dashboard/messages/'
    | '/_dashboard/pending-approvals/'
    | '/_dashboard/performance/'
    | '/_dashboard/properties/'
    | '/_dashboard/settings/'
    | '/_dashboard/users/'
    | '/_landing/about/'
    | '/_landing/blog/'
    | '/_landing/buy/'
    | '/_landing/contact/'
    | '/_landing/pricing/'
    | '/_landing/rent/'
    | '/_landing/sell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/set-password': {
      id: '/_auth/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/password-reset-sent': {
      id: '/_auth/password-reset-sent'
      path: '/password-reset-sent'
      fullPath: '/password-reset-sent'
      preLoaderRoute: typeof AuthPasswordResetSentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account-ready': {
      id: '/_auth/account-ready'
      path: '/account-ready'
      fullPath: '/account-ready'
      preLoaderRoute: typeof AuthAccountReadyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_landing/sell/': {
      id: '/_landing/sell/'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof LandingSellIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/rent/': {
      id: '/_landing/rent/'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof LandingRentIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/pricing/': {
      id: '/_landing/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LandingPricingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/contact/': {
      id: '/_landing/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LandingContactIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/buy/': {
      id: '/_landing/buy/'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof LandingBuyIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/blog/': {
      id: '/_landing/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LandingBlogIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/about/': {
      id: '/_landing/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/properties/': {
      id: '/_dashboard/properties/'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof DashboardPropertiesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/performance/': {
      id: '/_dashboard/performance/'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof DashboardPerformanceIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pending-approvals/': {
      id: '/_dashboard/pending-approvals/'
      path: '/pending-approvals'
      fullPath: '/pending-approvals'
      preLoaderRoute: typeof DashboardPendingApprovalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/messages/': {
      id: '/_dashboard/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof DashboardMessagesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/managers/': {
      id: '/_dashboard/managers/'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof DashboardManagersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/listing/': {
      id: '/_dashboard/listing/'
      path: '/listing'
      fullPath: '/listing'
      preLoaderRoute: typeof DashboardListingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/insights/': {
      id: '/_dashboard/insights/'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof DashboardInsightsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/getting-started/': {
      id: '/_dashboard/getting-started/'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof DashboardGettingStartedIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/blogs/': {
      id: '/_dashboard/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof DashboardBlogsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin-insights/': {
      id: '/_dashboard/admin-insights/'
      path: '/admin-insights'
      fullPath: '/admin-insights'
      preLoaderRoute: typeof DashboardAdminInsightsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_landing/sell/$id': {
      id: '/_landing/sell/$id'
      path: '/sell/$id'
      fullPath: '/sell/$id'
      preLoaderRoute: typeof LandingSellIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/rent/$id': {
      id: '/_landing/rent/$id'
      path: '/rent/$id'
      fullPath: '/rent/$id'
      preLoaderRoute: typeof LandingRentIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/buy/$id': {
      id: '/_landing/buy/$id'
      path: '/buy/$id'
      fullPath: '/buy/$id'
      preLoaderRoute: typeof LandingBuyIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/blog/$id': {
      id: '/_landing/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof LandingBlogIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_dashboard/properties/create': {
      id: '/_dashboard/properties/create'
      path: '/properties/create'
      fullPath: '/properties/create'
      preLoaderRoute: typeof DashboardPropertiesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/properties/$id': {
      id: '/_dashboard/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof DashboardPropertiesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/listing/$id': {
      id: '/_dashboard/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof DashboardListingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/blogs/create': {
      id: '/_dashboard/blogs/create'
      path: '/blogs/create'
      fullPath: '/blogs/create'
      preLoaderRoute: typeof DashboardBlogsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountReadyRoute: typeof AuthAccountReadyRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPasswordResetSentRoute: typeof AuthPasswordResetSentRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountReadyRoute: AuthAccountReadyRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPasswordResetSentRoute: AuthPasswordResetSentRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardBlogsCreateRoute: typeof DashboardBlogsCreateRoute
  DashboardListingIdRoute: typeof DashboardListingIdRoute
  DashboardPropertiesIdRoute: typeof DashboardPropertiesIdRoute
  DashboardPropertiesCreateRoute: typeof DashboardPropertiesCreateRoute
  DashboardAdminInsightsIndexRoute: typeof DashboardAdminInsightsIndexRoute
  DashboardBlogsIndexRoute: typeof DashboardBlogsIndexRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardGettingStartedIndexRoute: typeof DashboardGettingStartedIndexRoute
  DashboardInsightsIndexRoute: typeof DashboardInsightsIndexRoute
  DashboardListingIndexRoute: typeof DashboardListingIndexRoute
  DashboardManagersIndexRoute: typeof DashboardManagersIndexRoute
  DashboardMessagesIndexRoute: typeof DashboardMessagesIndexRoute
  DashboardPendingApprovalsIndexRoute: typeof DashboardPendingApprovalsIndexRoute
  DashboardPerformanceIndexRoute: typeof DashboardPerformanceIndexRoute
  DashboardPropertiesIndexRoute: typeof DashboardPropertiesIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBlogsCreateRoute: DashboardBlogsCreateRoute,
  DashboardListingIdRoute: DashboardListingIdRoute,
  DashboardPropertiesIdRoute: DashboardPropertiesIdRoute,
  DashboardPropertiesCreateRoute: DashboardPropertiesCreateRoute,
  DashboardAdminInsightsIndexRoute: DashboardAdminInsightsIndexRoute,
  DashboardBlogsIndexRoute: DashboardBlogsIndexRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardGettingStartedIndexRoute: DashboardGettingStartedIndexRoute,
  DashboardInsightsIndexRoute: DashboardInsightsIndexRoute,
  DashboardListingIndexRoute: DashboardListingIndexRoute,
  DashboardManagersIndexRoute: DashboardManagersIndexRoute,
  DashboardMessagesIndexRoute: DashboardMessagesIndexRoute,
  DashboardPendingApprovalsIndexRoute: DashboardPendingApprovalsIndexRoute,
  DashboardPerformanceIndexRoute: DashboardPerformanceIndexRoute,
  DashboardPropertiesIndexRoute: DashboardPropertiesIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LandingRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
  LandingBlogIdRoute: typeof LandingBlogIdRoute
  LandingBuyIdRoute: typeof LandingBuyIdRoute
  LandingRentIdRoute: typeof LandingRentIdRoute
  LandingSellIdRoute: typeof LandingSellIdRoute
  LandingAboutIndexRoute: typeof LandingAboutIndexRoute
  LandingBlogIndexRoute: typeof LandingBlogIndexRoute
  LandingBuyIndexRoute: typeof LandingBuyIndexRoute
  LandingContactIndexRoute: typeof LandingContactIndexRoute
  LandingPricingIndexRoute: typeof LandingPricingIndexRoute
  LandingRentIndexRoute: typeof LandingRentIndexRoute
  LandingSellIndexRoute: typeof LandingSellIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
  LandingBlogIdRoute: LandingBlogIdRoute,
  LandingBuyIdRoute: LandingBuyIdRoute,
  LandingRentIdRoute: LandingRentIdRoute,
  LandingSellIdRoute: LandingSellIdRoute,
  LandingAboutIndexRoute: LandingAboutIndexRoute,
  LandingBlogIndexRoute: LandingBlogIndexRoute,
  LandingBuyIndexRoute: LandingBuyIndexRoute,
  LandingContactIndexRoute: LandingContactIndexRoute,
  LandingPricingIndexRoute: LandingPricingIndexRoute,
  LandingRentIndexRoute: LandingRentIndexRoute,
  LandingSellIndexRoute: LandingSellIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
