/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthUnauthorizedRouteImport } from './routes/_auth/unauthorized'
import { Route as AuthSetPasswordRouteImport } from './routes/_auth/set-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthPasswordResetSentRouteImport } from './routes/_auth/password-reset-sent'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthAccountReadyRouteImport } from './routes/_auth/account-ready'
import { Route as LandingShortLetIndexRouteImport } from './routes/_landing/short-let/index'
import { Route as LandingPrivacyIndexRouteImport } from './routes/_landing/privacy/index'
import { Route as LandingPricingIndexRouteImport } from './routes/_landing/pricing/index'
import { Route as LandingJointVentureIndexRouteImport } from './routes/_landing/joint-venture/index'
import { Route as LandingForSaleIndexRouteImport } from './routes/_landing/for-sale/index'
import { Route as LandingForRentIndexRouteImport } from './routes/_landing/for-rent/index'
import { Route as LandingContactIndexRouteImport } from './routes/_landing/contact/index'
import { Route as LandingBlogIndexRouteImport } from './routes/_landing/blog/index'
import { Route as LandingAboutIndexRouteImport } from './routes/_landing/about/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardPropertiesIndexRouteImport } from './routes/_dashboard/properties/index'
import { Route as DashboardPerformanceIndexRouteImport } from './routes/_dashboard/performance/index'
import { Route as DashboardPendingApprovalsIndexRouteImport } from './routes/_dashboard/pending-approvals/index'
import { Route as DashboardNotificationsIndexRouteImport } from './routes/_dashboard/notifications/index'
import { Route as DashboardMessagesIndexRouteImport } from './routes/_dashboard/messages/index'
import { Route as DashboardManagersIndexRouteImport } from './routes/_dashboard/managers/index'
import { Route as DashboardListingIndexRouteImport } from './routes/_dashboard/listing/index'
import { Route as DashboardInsightsIndexRouteImport } from './routes/_dashboard/insights/index'
import { Route as DashboardGettingStartedIndexRouteImport } from './routes/_dashboard/getting-started/index'
import { Route as DashboardFavoritesIndexRouteImport } from './routes/_dashboard/favorites/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardBlogsIndexRouteImport } from './routes/_dashboard/blogs/index'
import { Route as DashboardAdminListingIndexRouteImport } from './routes/_dashboard/admin-listing/index'
import { Route as DashboardAdminInsightsIndexRouteImport } from './routes/_dashboard/admin-insights/index'
import { Route as LandingShortLetIdRouteImport } from './routes/_landing/short-let/$id'
import { Route as LandingJointVentureIdRouteImport } from './routes/_landing/joint-venture/$id'
import { Route as LandingForSaleIdRouteImport } from './routes/_landing/for-sale/$id'
import { Route as LandingForRentIdRouteImport } from './routes/_landing/for-rent/$id'
import { Route as LandingBlogIdRouteImport } from './routes/_landing/blog/$id'
import { Route as DashboardPropertiesCreateRouteImport } from './routes/_dashboard/properties/create'
import { Route as DashboardPropertiesIdRouteImport } from './routes/_dashboard/properties/$id'
import { Route as DashboardListingIdRouteImport } from './routes/_dashboard/listing/$id'
import { Route as DashboardBlogsCreateRouteImport } from './routes/_dashboard/blogs/create'
import { Route as DashboardAdminListingIdRouteImport } from './routes/_dashboard/admin-listing/$id'
import { Route as LandingShortLetPropertySubTypeStateLgaIdRouteImport } from './routes/_landing/short-let/$propertySubType/$state/$lga/$id'
import { Route as LandingJointVenturePropertySubTypeStateLgaIdRouteImport } from './routes/_landing/joint-venture/$propertySubType/$state/$lga/$id'
import { Route as LandingForSalePropertySubTypeStateLgaIdRouteImport } from './routes/_landing/for-sale/$propertySubType/$state/$lga/$id'
import { Route as LandingForRentPropertySubTypeStateLgaIdRouteImport } from './routes/_landing/for-rent/$propertySubType/$state/$lga/$id'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPasswordResetSentRoute = AuthPasswordResetSentRouteImport.update({
  id: '/password-reset-sent',
  path: '/password-reset-sent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountReadyRoute = AuthAccountReadyRouteImport.update({
  id: '/account-ready',
  path: '/account-ready',
  getParentRoute: () => AuthRoute,
} as any)
const LandingShortLetIndexRoute = LandingShortLetIndexRouteImport.update({
  id: '/short-let/',
  path: '/short-let/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPrivacyIndexRoute = LandingPrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPricingIndexRoute = LandingPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingJointVentureIndexRoute =
  LandingJointVentureIndexRouteImport.update({
    id: '/joint-venture/',
    path: '/joint-venture/',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingForSaleIndexRoute = LandingForSaleIndexRouteImport.update({
  id: '/for-sale/',
  path: '/for-sale/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingForRentIndexRoute = LandingForRentIndexRouteImport.update({
  id: '/for-rent/',
  path: '/for-rent/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingContactIndexRoute = LandingContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBlogIndexRoute = LandingBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAboutIndexRoute = LandingAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesIndexRoute =
  DashboardPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPerformanceIndexRoute =
  DashboardPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPendingApprovalsIndexRoute =
  DashboardPendingApprovalsIndexRouteImport.update({
    id: '/pending-approvals/',
    path: '/pending-approvals/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMessagesIndexRoute = DashboardMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManagersIndexRoute = DashboardManagersIndexRouteImport.update({
  id: '/managers/',
  path: '/managers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingIndexRoute = DashboardListingIndexRouteImport.update({
  id: '/listing/',
  path: '/listing/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsIndexRoute = DashboardInsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGettingStartedIndexRoute =
  DashboardGettingStartedIndexRouteImport.update({
    id: '/getting-started/',
    path: '/getting-started/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFavoritesIndexRoute = DashboardFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogsIndexRoute = DashboardBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminListingIndexRoute =
  DashboardAdminListingIndexRouteImport.update({
    id: '/admin-listing/',
    path: '/admin-listing/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminInsightsIndexRoute =
  DashboardAdminInsightsIndexRouteImport.update({
    id: '/admin-insights/',
    path: '/admin-insights/',
    getParentRoute: () => DashboardRoute,
  } as any)
const LandingShortLetIdRoute = LandingShortLetIdRouteImport.update({
  id: '/short-let/$id',
  path: '/short-let/$id',
  getParentRoute: () => LandingRoute,
} as any)
const LandingJointVentureIdRoute = LandingJointVentureIdRouteImport.update({
  id: '/joint-venture/$id',
  path: '/joint-venture/$id',
  getParentRoute: () => LandingRoute,
} as any)
const LandingForSaleIdRoute = LandingForSaleIdRouteImport.update({
  id: '/for-sale/$id',
  path: '/for-sale/$id',
  getParentRoute: () => LandingRoute,
} as any)
const LandingForRentIdRoute = LandingForRentIdRouteImport.update({
  id: '/for-rent/$id',
  path: '/for-rent/$id',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBlogIdRoute = LandingBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardPropertiesCreateRoute =
  DashboardPropertiesCreateRouteImport.update({
    id: '/properties/create',
    path: '/properties/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPropertiesIdRoute = DashboardPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingIdRoute = DashboardListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogsCreateRoute = DashboardBlogsCreateRouteImport.update({
  id: '/blogs/create',
  path: '/blogs/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminListingIdRoute = DashboardAdminListingIdRouteImport.update({
  id: '/admin-listing/$id',
  path: '/admin-listing/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const LandingShortLetPropertySubTypeStateLgaIdRoute =
  LandingShortLetPropertySubTypeStateLgaIdRouteImport.update({
    id: '/short-let/$propertySubType/$state/$lga/$id',
    path: '/short-let/$propertySubType/$state/$lga/$id',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingJointVenturePropertySubTypeStateLgaIdRoute =
  LandingJointVenturePropertySubTypeStateLgaIdRouteImport.update({
    id: '/joint-venture/$propertySubType/$state/$lga/$id',
    path: '/joint-venture/$propertySubType/$state/$lga/$id',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingForSalePropertySubTypeStateLgaIdRoute =
  LandingForSalePropertySubTypeStateLgaIdRouteImport.update({
    id: '/for-sale/$propertySubType/$state/$lga/$id',
    path: '/for-sale/$propertySubType/$state/$lga/$id',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingForRentPropertySubTypeStateLgaIdRoute =
  LandingForRentPropertySubTypeStateLgaIdRouteImport.update({
    id: '/for-rent/$propertySubType/$state/$lga/$id',
    path: '/for-rent/$propertySubType/$state/$lga/$id',
    getParentRoute: () => LandingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/account-ready': typeof AuthAccountReadyRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/password-reset-sent': typeof AuthPasswordResetSentRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-password': typeof AuthSetPasswordRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/admin-listing/$id': typeof DashboardAdminListingIdRoute
  '/blogs/create': typeof DashboardBlogsCreateRoute
  '/listing/$id': typeof DashboardListingIdRoute
  '/properties/$id': typeof DashboardPropertiesIdRoute
  '/properties/create': typeof DashboardPropertiesCreateRoute
  '/blog/$id': typeof LandingBlogIdRoute
  '/for-rent/$id': typeof LandingForRentIdRoute
  '/for-sale/$id': typeof LandingForSaleIdRoute
  '/joint-venture/$id': typeof LandingJointVentureIdRoute
  '/short-let/$id': typeof LandingShortLetIdRoute
  '/admin-insights/': typeof DashboardAdminInsightsIndexRoute
  '/admin-listing/': typeof DashboardAdminListingIndexRoute
  '/blogs/': typeof DashboardBlogsIndexRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/favorites/': typeof DashboardFavoritesIndexRoute
  '/getting-started/': typeof DashboardGettingStartedIndexRoute
  '/insights/': typeof DashboardInsightsIndexRoute
  '/listing/': typeof DashboardListingIndexRoute
  '/managers/': typeof DashboardManagersIndexRoute
  '/messages/': typeof DashboardMessagesIndexRoute
  '/notifications/': typeof DashboardNotificationsIndexRoute
  '/pending-approvals/': typeof DashboardPendingApprovalsIndexRoute
  '/performance/': typeof DashboardPerformanceIndexRoute
  '/properties/': typeof DashboardPropertiesIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/users/': typeof DashboardUsersIndexRoute
  '/about/': typeof LandingAboutIndexRoute
  '/blog/': typeof LandingBlogIndexRoute
  '/contact/': typeof LandingContactIndexRoute
  '/for-rent/': typeof LandingForRentIndexRoute
  '/for-sale/': typeof LandingForSaleIndexRoute
  '/joint-venture/': typeof LandingJointVentureIndexRoute
  '/pricing/': typeof LandingPricingIndexRoute
  '/privacy/': typeof LandingPrivacyIndexRoute
  '/short-let/': typeof LandingShortLetIndexRoute
  '/for-rent/$propertySubType/$state/$lga/$id': typeof LandingForRentPropertySubTypeStateLgaIdRoute
  '/for-sale/$propertySubType/$state/$lga/$id': typeof LandingForSalePropertySubTypeStateLgaIdRoute
  '/joint-venture/$propertySubType/$state/$lga/$id': typeof LandingJointVenturePropertySubTypeStateLgaIdRoute
  '/short-let/$propertySubType/$state/$lga/$id': typeof LandingShortLetPropertySubTypeStateLgaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/account-ready': typeof AuthAccountReadyRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/password-reset-sent': typeof AuthPasswordResetSentRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-password': typeof AuthSetPasswordRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/admin-listing/$id': typeof DashboardAdminListingIdRoute
  '/blogs/create': typeof DashboardBlogsCreateRoute
  '/listing/$id': typeof DashboardListingIdRoute
  '/properties/$id': typeof DashboardPropertiesIdRoute
  '/properties/create': typeof DashboardPropertiesCreateRoute
  '/blog/$id': typeof LandingBlogIdRoute
  '/for-rent/$id': typeof LandingForRentIdRoute
  '/for-sale/$id': typeof LandingForSaleIdRoute
  '/joint-venture/$id': typeof LandingJointVentureIdRoute
  '/short-let/$id': typeof LandingShortLetIdRoute
  '/admin-insights': typeof DashboardAdminInsightsIndexRoute
  '/admin-listing': typeof DashboardAdminListingIndexRoute
  '/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/favorites': typeof DashboardFavoritesIndexRoute
  '/getting-started': typeof DashboardGettingStartedIndexRoute
  '/insights': typeof DashboardInsightsIndexRoute
  '/listing': typeof DashboardListingIndexRoute
  '/managers': typeof DashboardManagersIndexRoute
  '/messages': typeof DashboardMessagesIndexRoute
  '/notifications': typeof DashboardNotificationsIndexRoute
  '/pending-approvals': typeof DashboardPendingApprovalsIndexRoute
  '/performance': typeof DashboardPerformanceIndexRoute
  '/properties': typeof DashboardPropertiesIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/about': typeof LandingAboutIndexRoute
  '/blog': typeof LandingBlogIndexRoute
  '/contact': typeof LandingContactIndexRoute
  '/for-rent': typeof LandingForRentIndexRoute
  '/for-sale': typeof LandingForSaleIndexRoute
  '/joint-venture': typeof LandingJointVentureIndexRoute
  '/pricing': typeof LandingPricingIndexRoute
  '/privacy': typeof LandingPrivacyIndexRoute
  '/short-let': typeof LandingShortLetIndexRoute
  '/for-rent/$propertySubType/$state/$lga/$id': typeof LandingForRentPropertySubTypeStateLgaIdRoute
  '/for-sale/$propertySubType/$state/$lga/$id': typeof LandingForSalePropertySubTypeStateLgaIdRoute
  '/joint-venture/$propertySubType/$state/$lga/$id': typeof LandingJointVenturePropertySubTypeStateLgaIdRoute
  '/short-let/$propertySubType/$state/$lga/$id': typeof LandingShortLetPropertySubTypeStateLgaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_auth/account-ready': typeof AuthAccountReadyRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/password-reset-sent': typeof AuthPasswordResetSentRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/set-password': typeof AuthSetPasswordRoute
  '/_auth/unauthorized': typeof AuthUnauthorizedRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_landing/': typeof LandingIndexRoute
  '/_dashboard/admin-listing/$id': typeof DashboardAdminListingIdRoute
  '/_dashboard/blogs/create': typeof DashboardBlogsCreateRoute
  '/_dashboard/listing/$id': typeof DashboardListingIdRoute
  '/_dashboard/properties/$id': typeof DashboardPropertiesIdRoute
  '/_dashboard/properties/create': typeof DashboardPropertiesCreateRoute
  '/_landing/blog/$id': typeof LandingBlogIdRoute
  '/_landing/for-rent/$id': typeof LandingForRentIdRoute
  '/_landing/for-sale/$id': typeof LandingForSaleIdRoute
  '/_landing/joint-venture/$id': typeof LandingJointVentureIdRoute
  '/_landing/short-let/$id': typeof LandingShortLetIdRoute
  '/_dashboard/admin-insights/': typeof DashboardAdminInsightsIndexRoute
  '/_dashboard/admin-listing/': typeof DashboardAdminListingIndexRoute
  '/_dashboard/blogs/': typeof DashboardBlogsIndexRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/favorites/': typeof DashboardFavoritesIndexRoute
  '/_dashboard/getting-started/': typeof DashboardGettingStartedIndexRoute
  '/_dashboard/insights/': typeof DashboardInsightsIndexRoute
  '/_dashboard/listing/': typeof DashboardListingIndexRoute
  '/_dashboard/managers/': typeof DashboardManagersIndexRoute
  '/_dashboard/messages/': typeof DashboardMessagesIndexRoute
  '/_dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/_dashboard/pending-approvals/': typeof DashboardPendingApprovalsIndexRoute
  '/_dashboard/performance/': typeof DashboardPerformanceIndexRoute
  '/_dashboard/properties/': typeof DashboardPropertiesIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
  '/_landing/about/': typeof LandingAboutIndexRoute
  '/_landing/blog/': typeof LandingBlogIndexRoute
  '/_landing/contact/': typeof LandingContactIndexRoute
  '/_landing/for-rent/': typeof LandingForRentIndexRoute
  '/_landing/for-sale/': typeof LandingForSaleIndexRoute
  '/_landing/joint-venture/': typeof LandingJointVentureIndexRoute
  '/_landing/pricing/': typeof LandingPricingIndexRoute
  '/_landing/privacy/': typeof LandingPrivacyIndexRoute
  '/_landing/short-let/': typeof LandingShortLetIndexRoute
  '/_landing/for-rent/$propertySubType/$state/$lga/$id': typeof LandingForRentPropertySubTypeStateLgaIdRoute
  '/_landing/for-sale/$propertySubType/$state/$lga/$id': typeof LandingForSalePropertySubTypeStateLgaIdRoute
  '/_landing/joint-venture/$propertySubType/$state/$lga/$id': typeof LandingJointVenturePropertySubTypeStateLgaIdRoute
  '/_landing/short-let/$propertySubType/$state/$lga/$id': typeof LandingShortLetPropertySubTypeStateLgaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-ready'
    | '/forgot-password'
    | '/login'
    | '/password-reset-sent'
    | '/register'
    | '/reset-password'
    | '/set-password'
    | '/unauthorized'
    | '/verify-otp'
    | '/admin-listing/$id'
    | '/blogs/create'
    | '/listing/$id'
    | '/properties/$id'
    | '/properties/create'
    | '/blog/$id'
    | '/for-rent/$id'
    | '/for-sale/$id'
    | '/joint-venture/$id'
    | '/short-let/$id'
    | '/admin-insights/'
    | '/admin-listing/'
    | '/blogs/'
    | '/dashboard/'
    | '/favorites/'
    | '/getting-started/'
    | '/insights/'
    | '/listing/'
    | '/managers/'
    | '/messages/'
    | '/notifications/'
    | '/pending-approvals/'
    | '/performance/'
    | '/properties/'
    | '/settings/'
    | '/users/'
    | '/about/'
    | '/blog/'
    | '/contact/'
    | '/for-rent/'
    | '/for-sale/'
    | '/joint-venture/'
    | '/pricing/'
    | '/privacy/'
    | '/short-let/'
    | '/for-rent/$propertySubType/$state/$lga/$id'
    | '/for-sale/$propertySubType/$state/$lga/$id'
    | '/joint-venture/$propertySubType/$state/$lga/$id'
    | '/short-let/$propertySubType/$state/$lga/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-ready'
    | '/forgot-password'
    | '/login'
    | '/password-reset-sent'
    | '/register'
    | '/reset-password'
    | '/set-password'
    | '/unauthorized'
    | '/verify-otp'
    | '/admin-listing/$id'
    | '/blogs/create'
    | '/listing/$id'
    | '/properties/$id'
    | '/properties/create'
    | '/blog/$id'
    | '/for-rent/$id'
    | '/for-sale/$id'
    | '/joint-venture/$id'
    | '/short-let/$id'
    | '/admin-insights'
    | '/admin-listing'
    | '/blogs'
    | '/dashboard'
    | '/favorites'
    | '/getting-started'
    | '/insights'
    | '/listing'
    | '/managers'
    | '/messages'
    | '/notifications'
    | '/pending-approvals'
    | '/performance'
    | '/properties'
    | '/settings'
    | '/users'
    | '/about'
    | '/blog'
    | '/contact'
    | '/for-rent'
    | '/for-sale'
    | '/joint-venture'
    | '/pricing'
    | '/privacy'
    | '/short-let'
    | '/for-rent/$propertySubType/$state/$lga/$id'
    | '/for-sale/$propertySubType/$state/$lga/$id'
    | '/joint-venture/$propertySubType/$state/$lga/$id'
    | '/short-let/$propertySubType/$state/$lga/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_landing'
    | '/_auth/account-ready'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/password-reset-sent'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/set-password'
    | '/_auth/unauthorized'
    | '/_auth/verify-otp'
    | '/_landing/'
    | '/_dashboard/admin-listing/$id'
    | '/_dashboard/blogs/create'
    | '/_dashboard/listing/$id'
    | '/_dashboard/properties/$id'
    | '/_dashboard/properties/create'
    | '/_landing/blog/$id'
    | '/_landing/for-rent/$id'
    | '/_landing/for-sale/$id'
    | '/_landing/joint-venture/$id'
    | '/_landing/short-let/$id'
    | '/_dashboard/admin-insights/'
    | '/_dashboard/admin-listing/'
    | '/_dashboard/blogs/'
    | '/_dashboard/dashboard/'
    | '/_dashboard/favorites/'
    | '/_dashboard/getting-started/'
    | '/_dashboard/insights/'
    | '/_dashboard/listing/'
    | '/_dashboard/managers/'
    | '/_dashboard/messages/'
    | '/_dashboard/notifications/'
    | '/_dashboard/pending-approvals/'
    | '/_dashboard/performance/'
    | '/_dashboard/properties/'
    | '/_dashboard/settings/'
    | '/_dashboard/users/'
    | '/_landing/about/'
    | '/_landing/blog/'
    | '/_landing/contact/'
    | '/_landing/for-rent/'
    | '/_landing/for-sale/'
    | '/_landing/joint-venture/'
    | '/_landing/pricing/'
    | '/_landing/privacy/'
    | '/_landing/short-let/'
    | '/_landing/for-rent/$propertySubType/$state/$lga/$id'
    | '/_landing/for-sale/$propertySubType/$state/$lga/$id'
    | '/_landing/joint-venture/$propertySubType/$state/$lga/$id'
    | '/_landing/short-let/$propertySubType/$state/$lga/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/unauthorized': {
      id: '/_auth/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/set-password': {
      id: '/_auth/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/password-reset-sent': {
      id: '/_auth/password-reset-sent'
      path: '/password-reset-sent'
      fullPath: '/password-reset-sent'
      preLoaderRoute: typeof AuthPasswordResetSentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account-ready': {
      id: '/_auth/account-ready'
      path: '/account-ready'
      fullPath: '/account-ready'
      preLoaderRoute: typeof AuthAccountReadyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_landing/short-let/': {
      id: '/_landing/short-let/'
      path: '/short-let'
      fullPath: '/short-let/'
      preLoaderRoute: typeof LandingShortLetIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/privacy/': {
      id: '/_landing/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof LandingPrivacyIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/pricing/': {
      id: '/_landing/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof LandingPricingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/joint-venture/': {
      id: '/_landing/joint-venture/'
      path: '/joint-venture'
      fullPath: '/joint-venture/'
      preLoaderRoute: typeof LandingJointVentureIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/for-sale/': {
      id: '/_landing/for-sale/'
      path: '/for-sale'
      fullPath: '/for-sale/'
      preLoaderRoute: typeof LandingForSaleIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/for-rent/': {
      id: '/_landing/for-rent/'
      path: '/for-rent'
      fullPath: '/for-rent/'
      preLoaderRoute: typeof LandingForRentIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/contact/': {
      id: '/_landing/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof LandingContactIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/blog/': {
      id: '/_landing/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof LandingBlogIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/about/': {
      id: '/_landing/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof LandingAboutIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/properties/': {
      id: '/_dashboard/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof DashboardPropertiesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/performance/': {
      id: '/_dashboard/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof DashboardPerformanceIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pending-approvals/': {
      id: '/_dashboard/pending-approvals/'
      path: '/pending-approvals'
      fullPath: '/pending-approvals/'
      preLoaderRoute: typeof DashboardPendingApprovalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/notifications/': {
      id: '/_dashboard/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof DashboardNotificationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/messages/': {
      id: '/_dashboard/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof DashboardMessagesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/managers/': {
      id: '/_dashboard/managers/'
      path: '/managers'
      fullPath: '/managers/'
      preLoaderRoute: typeof DashboardManagersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/listing/': {
      id: '/_dashboard/listing/'
      path: '/listing'
      fullPath: '/listing/'
      preLoaderRoute: typeof DashboardListingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/insights/': {
      id: '/_dashboard/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof DashboardInsightsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/getting-started/': {
      id: '/_dashboard/getting-started/'
      path: '/getting-started'
      fullPath: '/getting-started/'
      preLoaderRoute: typeof DashboardGettingStartedIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/favorites/': {
      id: '/_dashboard/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof DashboardFavoritesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/blogs/': {
      id: '/_dashboard/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof DashboardBlogsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin-listing/': {
      id: '/_dashboard/admin-listing/'
      path: '/admin-listing'
      fullPath: '/admin-listing/'
      preLoaderRoute: typeof DashboardAdminListingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin-insights/': {
      id: '/_dashboard/admin-insights/'
      path: '/admin-insights'
      fullPath: '/admin-insights/'
      preLoaderRoute: typeof DashboardAdminInsightsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_landing/short-let/$id': {
      id: '/_landing/short-let/$id'
      path: '/short-let/$id'
      fullPath: '/short-let/$id'
      preLoaderRoute: typeof LandingShortLetIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/joint-venture/$id': {
      id: '/_landing/joint-venture/$id'
      path: '/joint-venture/$id'
      fullPath: '/joint-venture/$id'
      preLoaderRoute: typeof LandingJointVentureIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/for-sale/$id': {
      id: '/_landing/for-sale/$id'
      path: '/for-sale/$id'
      fullPath: '/for-sale/$id'
      preLoaderRoute: typeof LandingForSaleIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/for-rent/$id': {
      id: '/_landing/for-rent/$id'
      path: '/for-rent/$id'
      fullPath: '/for-rent/$id'
      preLoaderRoute: typeof LandingForRentIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/blog/$id': {
      id: '/_landing/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof LandingBlogIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_dashboard/properties/create': {
      id: '/_dashboard/properties/create'
      path: '/properties/create'
      fullPath: '/properties/create'
      preLoaderRoute: typeof DashboardPropertiesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/properties/$id': {
      id: '/_dashboard/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof DashboardPropertiesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/listing/$id': {
      id: '/_dashboard/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof DashboardListingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/blogs/create': {
      id: '/_dashboard/blogs/create'
      path: '/blogs/create'
      fullPath: '/blogs/create'
      preLoaderRoute: typeof DashboardBlogsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin-listing/$id': {
      id: '/_dashboard/admin-listing/$id'
      path: '/admin-listing/$id'
      fullPath: '/admin-listing/$id'
      preLoaderRoute: typeof DashboardAdminListingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_landing/short-let/$propertySubType/$state/$lga/$id': {
      id: '/_landing/short-let/$propertySubType/$state/$lga/$id'
      path: '/short-let/$propertySubType/$state/$lga/$id'
      fullPath: '/short-let/$propertySubType/$state/$lga/$id'
      preLoaderRoute: typeof LandingShortLetPropertySubTypeStateLgaIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/joint-venture/$propertySubType/$state/$lga/$id': {
      id: '/_landing/joint-venture/$propertySubType/$state/$lga/$id'
      path: '/joint-venture/$propertySubType/$state/$lga/$id'
      fullPath: '/joint-venture/$propertySubType/$state/$lga/$id'
      preLoaderRoute: typeof LandingJointVenturePropertySubTypeStateLgaIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/for-sale/$propertySubType/$state/$lga/$id': {
      id: '/_landing/for-sale/$propertySubType/$state/$lga/$id'
      path: '/for-sale/$propertySubType/$state/$lga/$id'
      fullPath: '/for-sale/$propertySubType/$state/$lga/$id'
      preLoaderRoute: typeof LandingForSalePropertySubTypeStateLgaIdRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/for-rent/$propertySubType/$state/$lga/$id': {
      id: '/_landing/for-rent/$propertySubType/$state/$lga/$id'
      path: '/for-rent/$propertySubType/$state/$lga/$id'
      fullPath: '/for-rent/$propertySubType/$state/$lga/$id'
      preLoaderRoute: typeof LandingForRentPropertySubTypeStateLgaIdRouteImport
      parentRoute: typeof LandingRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountReadyRoute: typeof AuthAccountReadyRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPasswordResetSentRoute: typeof AuthPasswordResetSentRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountReadyRoute: AuthAccountReadyRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPasswordResetSentRoute: AuthPasswordResetSentRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminListingIdRoute: typeof DashboardAdminListingIdRoute
  DashboardBlogsCreateRoute: typeof DashboardBlogsCreateRoute
  DashboardListingIdRoute: typeof DashboardListingIdRoute
  DashboardPropertiesIdRoute: typeof DashboardPropertiesIdRoute
  DashboardPropertiesCreateRoute: typeof DashboardPropertiesCreateRoute
  DashboardAdminInsightsIndexRoute: typeof DashboardAdminInsightsIndexRoute
  DashboardAdminListingIndexRoute: typeof DashboardAdminListingIndexRoute
  DashboardBlogsIndexRoute: typeof DashboardBlogsIndexRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardFavoritesIndexRoute: typeof DashboardFavoritesIndexRoute
  DashboardGettingStartedIndexRoute: typeof DashboardGettingStartedIndexRoute
  DashboardInsightsIndexRoute: typeof DashboardInsightsIndexRoute
  DashboardListingIndexRoute: typeof DashboardListingIndexRoute
  DashboardManagersIndexRoute: typeof DashboardManagersIndexRoute
  DashboardMessagesIndexRoute: typeof DashboardMessagesIndexRoute
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
  DashboardPendingApprovalsIndexRoute: typeof DashboardPendingApprovalsIndexRoute
  DashboardPerformanceIndexRoute: typeof DashboardPerformanceIndexRoute
  DashboardPropertiesIndexRoute: typeof DashboardPropertiesIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminListingIdRoute: DashboardAdminListingIdRoute,
  DashboardBlogsCreateRoute: DashboardBlogsCreateRoute,
  DashboardListingIdRoute: DashboardListingIdRoute,
  DashboardPropertiesIdRoute: DashboardPropertiesIdRoute,
  DashboardPropertiesCreateRoute: DashboardPropertiesCreateRoute,
  DashboardAdminInsightsIndexRoute: DashboardAdminInsightsIndexRoute,
  DashboardAdminListingIndexRoute: DashboardAdminListingIndexRoute,
  DashboardBlogsIndexRoute: DashboardBlogsIndexRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardFavoritesIndexRoute: DashboardFavoritesIndexRoute,
  DashboardGettingStartedIndexRoute: DashboardGettingStartedIndexRoute,
  DashboardInsightsIndexRoute: DashboardInsightsIndexRoute,
  DashboardListingIndexRoute: DashboardListingIndexRoute,
  DashboardManagersIndexRoute: DashboardManagersIndexRoute,
  DashboardMessagesIndexRoute: DashboardMessagesIndexRoute,
  DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  DashboardPendingApprovalsIndexRoute: DashboardPendingApprovalsIndexRoute,
  DashboardPerformanceIndexRoute: DashboardPerformanceIndexRoute,
  DashboardPropertiesIndexRoute: DashboardPropertiesIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LandingRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
  LandingBlogIdRoute: typeof LandingBlogIdRoute
  LandingForRentIdRoute: typeof LandingForRentIdRoute
  LandingForSaleIdRoute: typeof LandingForSaleIdRoute
  LandingJointVentureIdRoute: typeof LandingJointVentureIdRoute
  LandingShortLetIdRoute: typeof LandingShortLetIdRoute
  LandingAboutIndexRoute: typeof LandingAboutIndexRoute
  LandingBlogIndexRoute: typeof LandingBlogIndexRoute
  LandingContactIndexRoute: typeof LandingContactIndexRoute
  LandingForRentIndexRoute: typeof LandingForRentIndexRoute
  LandingForSaleIndexRoute: typeof LandingForSaleIndexRoute
  LandingJointVentureIndexRoute: typeof LandingJointVentureIndexRoute
  LandingPricingIndexRoute: typeof LandingPricingIndexRoute
  LandingPrivacyIndexRoute: typeof LandingPrivacyIndexRoute
  LandingShortLetIndexRoute: typeof LandingShortLetIndexRoute
  LandingForRentPropertySubTypeStateLgaIdRoute: typeof LandingForRentPropertySubTypeStateLgaIdRoute
  LandingForSalePropertySubTypeStateLgaIdRoute: typeof LandingForSalePropertySubTypeStateLgaIdRoute
  LandingJointVenturePropertySubTypeStateLgaIdRoute: typeof LandingJointVenturePropertySubTypeStateLgaIdRoute
  LandingShortLetPropertySubTypeStateLgaIdRoute: typeof LandingShortLetPropertySubTypeStateLgaIdRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
  LandingBlogIdRoute: LandingBlogIdRoute,
  LandingForRentIdRoute: LandingForRentIdRoute,
  LandingForSaleIdRoute: LandingForSaleIdRoute,
  LandingJointVentureIdRoute: LandingJointVentureIdRoute,
  LandingShortLetIdRoute: LandingShortLetIdRoute,
  LandingAboutIndexRoute: LandingAboutIndexRoute,
  LandingBlogIndexRoute: LandingBlogIndexRoute,
  LandingContactIndexRoute: LandingContactIndexRoute,
  LandingForRentIndexRoute: LandingForRentIndexRoute,
  LandingForSaleIndexRoute: LandingForSaleIndexRoute,
  LandingJointVentureIndexRoute: LandingJointVentureIndexRoute,
  LandingPricingIndexRoute: LandingPricingIndexRoute,
  LandingPrivacyIndexRoute: LandingPrivacyIndexRoute,
  LandingShortLetIndexRoute: LandingShortLetIndexRoute,
  LandingForRentPropertySubTypeStateLgaIdRoute:
    LandingForRentPropertySubTypeStateLgaIdRoute,
  LandingForSalePropertySubTypeStateLgaIdRoute:
    LandingForSalePropertySubTypeStateLgaIdRoute,
  LandingJointVenturePropertySubTypeStateLgaIdRoute:
    LandingJointVenturePropertySubTypeStateLgaIdRoute,
  LandingShortLetPropertySubTypeStateLgaIdRoute:
    LandingShortLetPropertySubTypeStateLgaIdRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
